# Generated by Django 4.2.1 on 2023-05-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
        ('academico', '0003_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculados_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, max_length=50)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cursos')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.matricula')),
            ],
        ),
    ]
