# Generated by Django 4.2.1 on 2023-06-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_matriculados_estudiante_estado_lista_estudiante'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carga_horaria',
            unique_together={('id_asignatura', 'id_curso')},
        ),
    ]
